// Generated by @glaze/sdk-toolkit

/**
 * @type {import('@glaze/types').GlazeConfig}
 */
const config = {
  plugins: [{
    id: '@glaze-plugin/click-heatmap',
    name: '点击热力图支持插件',
    /** 插件描述 */
    desc: '点击热力图支持插件，监听所有 Glaze 节点的点击事件并上传 Glaze 分析服务器',
    type: 'PUBLIC',
    main: './click-heatmap/index.ts'
  }, {
    id: '@glaze-plugin/focus-heatmap',
    name: '焦点热力图支持插件',
    /** 插件描述 */
    desc: '焦点热力图支持插件，监听所有元素的在用户视窗内的时间并上传 Glaze 分析服务器',
    type: 'PUBLIC',
    main: './focus-heatmap/index.ts'
  }],

  // Never change this object.
  generated: {
    ownerTeamId: 14
  }
}

module.exports = config
