// Generated by @glaze/sdk-toolkit

/**
 * @type {import('@glaze/types').GlazeConfig}
 */
const config = {
  plugins: [
    {
      id: '@glaze-plugin/click-heatmap',
      name: '点击热力图支持插件',
      desc: '点击热力图支持插件，监听所有 Glaze 节点的点击事件并上传 Glaze 分析服务器',
      type: 'PUBLIC',
      main: './click-heatmap/index.ts',
      icon: 'https://glaze-1257788062.cos.ap-nanjing.myqcloud.com/user/kunduin/icon.jpg',
    },
    {
      id: '@glaze-plugin/scroll-heatmap',
      name: '滚动热力图支持插件',
      desc: '滚动热力图支持插件，滚动消息，并将滚动消息上传到 Glaze 分析服务器',
      type: 'PUBLIC',
      main: './scroll-heatmap/index.ts',
      icon: 'https://glaze-1257788062.cos.ap-nanjing.myqcloud.com/user/kunduin/icon.jpg',
    },
    {
      id: '@glaze-plugin/schema-test',
      name: '配置信息测试插件',
      desc: '测试动态配置是否有效',
      type: 'PUBLIC',
      main: './schema-test/index.ts',
      icon: 'https://glaze-1257788062.cos.ap-nanjing.myqcloud.com/user/kunduin/icon.jpg',
      config: {
        string: {
          name: '字符串测试',
          type: 'text',
          default: 'string',
        },
        number: {
          name: '数字测试',
          type: 'number',
          default: 1,
          min: 0,
          max: 10,
        },
      },
    },
  ],

  // Never change this object.
  generated: {
    ownerTeamId: 14,
  },
}

module.exports = config
