// Generated by @glaze/sdk-toolkit

/**
 * @type {import('@glaze/types').GlazeConfig}
 */
const config = {
  plugins: [
    {
      id: '@glaze-plugin/component-A',
      name: '自定义组件A',
      desc: '自定义组件A',
      type: 'PUBLIC',
      main: './src/components/A/index.tsx',
      icon: 'https://glaze-1257788062.cos.ap-nanjing.myqcloud.com/user/kunduin/icon.jpg',
    },
  ],

  // Never change this object.
  generated: {
    ownerTeamId: 8
  }
}

module.exports = config
